Home Robot: A ROS 2 Jazzy package for Service Robotics Course at University of León: home_robot.overhead_cam_service.OverheadCamService Class Reference
home_robot.overhead_cam_service.OverheadCamService Class Reference
Service node that launches rqt_image_view for overhead camera visualization.
Public Member Functions
__init__ (self)
Initialize the overhead camera service.
destroy_node (self)
Clean up by terminating viewer subprocess.
Public Attributes
topic = self.get_parameter("topic").get_parameter_value().string_value
srv
Protected Member Functions
_handle_request (self, _request, response)
Handle service request to open camera viewer.
Protected Attributes
subprocess.Popen|None _process = None
Detailed Description
Service node that launches rqt_image_view for overhead camera visualization.
Manages a subprocess running rqt_image_view and ensures only one instance is active at a time.
Definition at line 26 of file overhead_cam_service.py.
Constructor & Destructor Documentation
__init__()
home_robot.overhead_cam_service.OverheadCamService.__init__ (self)
Initialize the overhead camera service.
Definition at line 34 of file overhead_cam_service.py.
    def __init__(self):
        """Initialize the overhead camera service."""
        super().__init__("overhead_cam_service")
        self.declare_parameter("topic", "/overhead_cam")
        self.topic = self.get_parameter("topic").get_parameter_value().string_value
        self.srv = self.create_service(
            Trigger, "overhead_cam", self._handle_request
        )
        self._process: subprocess.Popen | None = None
        self.get_logger().info(
            f"Overhead-cam service ready  →  topic: {self.topic}"
        )
References __init__().
Referenced by __init__().
Member Function Documentation
_handle_request()
home_robot.overhead_cam_service.OverheadCamService._handle_request (self, _request, response) protected
Handle service request to open camera viewer.
Args: _request: Trigger request (empty) response: Trigger response with success status and message
Returns: response: Populated with success status and message
Definition at line 50 of file overhead_cam_service.py.
    def _handle_request(self, _request, response):
        """
        Handle service request to open camera viewer.
        Args:
            _request: Trigger request (empty)
            response: Trigger response with success status and message
        Returns:
            response: Populated with success status and message
        """
        # Prevent duplicate viewer windows
        if self._process is not None and self._process.poll() is None:
            response.success = False
            response.message = "Viewer window already open."
            self.get_logger().warn(response.message)
            return response
        try:
            # Launch rqt_image_view with topic remapping
            self._process = subprocess.Popen(
                [
                    "ros2", "run", "rqt_image_view", "rqt_image_view",
                    "--ros-args", "-r", f"image:={self.topic}",
                ],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            response.success = True
            response.message = (
                f"Overhead camera viewer opened on {self.topic}"
            )
            self.get_logger().info(response.message)
        except Exception as e:
            response.success = False
            response.message = f"Failed to open viewer: {e}"
            self.get_logger().error(response.message)
        return response
References _process.
destroy_node()
home_robot.overhead_cam_service.OverheadCamService.destroy_node (self)
Clean up by terminating viewer subprocess.
Definition at line 90 of file overhead_cam_service.py.
    def destroy_node(self):
        """Clean up by terminating viewer subprocess."""
        # Terminate rqt_image_view if still running
        if self._process is not None and self._process.poll() is None:
            self._process.terminate()
        super().destroy_node()
References _process, and destroy_node().
Referenced by destroy_node().
Member Data Documentation
_process
subprocess.Popen | None home_robot.overhead_cam_service.OverheadCamService._process = None protected
Definition at line 44 of file overhead_cam_service.py.
Referenced by _handle_request(), and destroy_node().
srv
home_robot.overhead_cam_service.OverheadCamService.srv
Initial value:
=  self.create_service(
            Trigger, "overhead_cam", self._handle_request
        )
Definition at line 41 of file overhead_cam_service.py.
topic
home_robot.overhead_cam_service.OverheadCamService.topic = self.get_parameter("topic").get_parameter_value().string_value
Definition at line 39 of file overhead_cam_service.py.
The documentation for this class was generated from the following file:
ros2_ws/src/home_robot/home_robot/overhead_cam_service.py