Home Robot: A ROS 2 Jazzy package for Service Robotics Course at University of León: home_robot.navigation_service.NavigationService Class Reference
home_robot.navigation_service.NavigationService Class Reference
ROS2 service node for simple pose-based navigation commands.
Public Member Functions
__init__ (self)
Initialize the navigation service and BasicNavigator.
go_to_pose_callback (self, request, response)
Handle navigation goal requests.
Public Attributes
nav = BasicNavigator()
srv
Detailed Description
ROS2 service node for simple pose-based navigation commands.
Wraps Nav2's BasicNavigator to provide a synchronous service interface for sending navigation goals.
Definition at line 27 of file navigation_service.py.
Constructor & Destructor Documentation
__init__()
home_robot.navigation_service.NavigationService.__init__ (self)
Initialize the navigation service and BasicNavigator.
Definition at line 35 of file navigation_service.py.
    def __init__(self):
        """Initialize the navigation service and BasicNavigator."""
        super().__init__('navigation_service_node')
        self.nav = BasicNavigator()
        # Create service using SetInitialPose message type for navigation
        # (reusing existing message type for simplicity)
        self.srv = self.create_service(
            SetInitialPose,
            'go_to_pose',
            self.go_to_pose_callback
        )
        self.get_logger().info('Service /go_to_pose ready (Type: nav2_msgs/srv/SetInitialPose)')
References __init__().
Referenced by __init__().
Member Function Documentation
go_to_pose_callback()
home_robot.navigation_service.NavigationService.go_to_pose_callback (self, request, response)
Handle navigation goal requests.
Args: request: SetInitialPose service request containing target pose response: Service response (empty, success implied)
Returns: response: Empty response indicating goal was accepted
Definition at line 49 of file navigation_service.py.
    def go_to_pose_callback(self, request, response):
        """
        Handle navigation goal requests.
        Args:
            request: SetInitialPose service request containing target pose
            response: Service response (empty, success implied)
        Returns:
            response: Empty response indicating goal was accepted
        """
        goal_pose = PoseStamped()
        goal_pose.header.frame_id = 'map'
        goal_pose.header.stamp = self.get_clock().now().to_msg()
        # Extract pose from request (SetInitialPose -> PoseWithCovarianceStamped -> Pose)
        goal_pose.pose = request.pose.pose.pose
        self.get_logger().info(f"Navigating to: x={goal_pose.pose.position.x}, y={goal_pose.pose.position.y}")
        # Send goal to Nav2
        self.nav.goToPose(goal_pose)
        # Note: This is a fire-and-forget service. Nav2 manages goal execution independently.
        # To wait for completion, add a loop checking self.nav.isTaskComplete()
        return response
References nav.
Member Data Documentation
nav
home_robot.navigation_service.NavigationService.nav = BasicNavigator()
Definition at line 38 of file navigation_service.py.
Referenced by home_robot.voice_controller.VoiceController.go_to(), go_to_pose_callback(), and home_robot.voice_controller.VoiceController.process_command().
srv
home_robot.navigation_service.NavigationService.srv
Initial value:
=  self.create_service(
            SetInitialPose,
            'go_to_pose',
            self.go_to_pose_callback
        )
Definition at line 42 of file navigation_service.py.
The documentation for this class was generated from the following file:
ros2_ws/src/home_robot/home_robot/navigation_service.py