Home Robot: A ROS 2 Jazzy package for Service Robotics Course at University of León: home_robot.navigation_manager.NavigationManager Class Reference
home_robot.navigation_manager.NavigationManager Class Reference
Manages waypoint navigation for the home robot.
Public Member Functions
__init__ (self)
Initialize NavigationManager node with parameters and BasicNavigator.
dict load_waypoints (self)
Load waypoints from YAML file.
dict euler_to_quaternion (self, float yaw)
Convert Euler yaw angle to quaternion representation.
run (self)
Execute waypoint navigation in sequential or random order.
speak (self, str text)
Log voice announcement (placeholder for TTS integration).
Public Attributes
waypoints_path = self.get_parameter('waypoints_file').get_parameter_value().string_value
str mode = self.get_parameter('mode').get_parameter_value().string_value
navigator = BasicNavigator()
dict waypoints = self.load_waypoints()
Detailed Description
Manages waypoint navigation for the home robot.
Definition at line 26 of file navigation_manager.py.
Constructor & Destructor Documentation
__init__()
home_robot.navigation_manager.NavigationManager.__init__ (self)
Initialize NavigationManager node with parameters and BasicNavigator.
Definition at line 29 of file navigation_manager.py.
    def __init__(self):
        """Initialize NavigationManager node with parameters and BasicNavigator."""
        super().__init__('navigation_manager')
        # Get default waypoints path from package
        pkg_share = get_package_share_directory('home_robot')
        default_wp_path = os.path.join(pkg_share, 'config', 'waypoints.yaml')
        # Declare dynamic parameters
        self.declare_parameter('waypoints_file', default_wp_path)
        self.declare_parameter('mode', 'sequential')  # sequential or random
        self.waypoints_path = self.get_parameter('waypoints_file').get_parameter_value().string_value
        self.mode = self.get_parameter('mode').get_parameter_value().string_value
        self.navigator = BasicNavigator()
        # Load waypoints from file
        self.waypoints = self.load_waypoints()
        if not self.waypoints:
            self.get_logger().error(f"Could not load waypoints from {self.waypoints_path}")
            return
        # Wait for Nav2 to become active
        self.get_logger().info("Waiting for Nav2 to activate (BT Navigator)...")
        # In Jazzy with SLAM Toolbox, we avoid waiting for localizer as it's not a standard lifecycle node
        self.navigator.waitUntilNav2Active(localizer='robot_state_publisher')
        self.get_logger().info("Nav2 ready.")
References __init__().
Referenced by __init__().
Member Function Documentation
euler_to_quaternion()
dict home_robot.navigation_manager.NavigationManager.euler_to_quaternion (self, float yaw)
Convert Euler yaw angle to quaternion representation.
Args: yaw: Yaw angle in radians
Returns: Dictionary with 'z' and 'w' quaternion components
Definition at line 75 of file navigation_manager.py.
    def euler_to_quaternion(self, yaw: float) -> dict:
        """Convert Euler yaw angle to quaternion representation.
        Args:
            yaw: Yaw angle in radians
        Returns:
            Dictionary with 'z' and 'w' quaternion components
        """
        return {
            'z': math.sin(yaw / 2),
            'w': math.cos(yaw / 2)
        }
Referenced by run().
load_waypoints()
dict home_robot.navigation_manager.NavigationManager.load_waypoints (self)
Load waypoints from YAML file.
Returns: Dictionary of waypoints with name as key and coordinates as value. Empty dict if file not found or parsing fails.
Definition at line 58 of file navigation_manager.py.
    def load_waypoints(self) -> dict:
        """Load waypoints from YAML file.
        Returns:
            Dictionary of waypoints with name as key and coordinates as value.
            Empty dict if file not found or parsing fails.
        """
        if not os.path.exists(self.waypoints_path):
            return {}
        try:
            with open(self.waypoints_path, 'r') as f:
                data = yaml.safe_load(f)
                return data.get('waypoints', {})
        except Exception as e:
            self.get_logger().error(f"Error reading waypoints file: {e}")
            return {}
References waypoints_path.
run()
home_robot.navigation_manager.NavigationManager.run (self)
Execute waypoint navigation in sequential or random order.
Navigates through all loaded waypoints, monitoring progress and handling navigation results (success, cancel, failure).
Definition at line 89 of file navigation_manager.py.
    def run(self):
        """Execute waypoint navigation in sequential or random order.
        Navigates through all loaded waypoints, monitoring progress and
        handling navigation results (success, cancel, failure).
        """
        wp_names = list(self.waypoints.keys())
        if self.mode == 'random':
            random.shuffle(wp_names)
            self.get_logger().info("Mode: Random")
        else:
            self.get_logger().info("Mode: Sequential")
        for name in wp_names:
            wp = self.waypoints[name]
            self.get_logger().info(f"Navigating to: {name} (x: {wp['x']}, y: {wp['y']})")
            goal_pose = PoseStamped()
            goal_pose.header.frame_id = 'map'
            goal_pose.header.stamp = self.navigator.get_clock().now().to_msg()
            goal_pose.pose.position.x = float(wp['x'])
            goal_pose.pose.position.y = float(wp['y'])
            q = self.euler_to_quaternion(float(wp['theta']))
            goal_pose.pose.orientation.z = q['z']
            goal_pose.pose.orientation.w = q['w']
            # Send robot to goal pose
            self.navigator.goToPose(goal_pose)
            # Monitor navigation progress
            while not self.navigator.isTaskComplete():
                feedback = self.navigator.getFeedback()
                if feedback:
                    pass
                time.sleep(1.0)
            # Check navigation result
            result = self.navigator.getResult()
            if result == TaskResult.SUCCEEDED:
                self.get_logger().info(f"Reached {name}!")
                # self.speak(f"He llegado a {name}")  # Commented: announcement done by voice_controller if active
                # Pause between waypoints
                time.sleep(2.0)
            elif result == TaskResult.CANCELED:
                self.get_logger().warn(f"Mission canceled for {name}.")
                break
            elif result == TaskResult.FAILED:
                self.get_logger().error(f"Failed to navigate to {name}.")
                break
References euler_to_quaternion(), mode, navigator, and waypoints.
speak()
home_robot.navigation_manager.NavigationManager.speak (self, str text)
Log voice announcement (placeholder for TTS integration).
Args: text: Text to be spoken
Definition at line 141 of file navigation_manager.py.
    def speak(self, text: str):
        """Log voice announcement (placeholder for TTS integration).
        Args:
            text: Text to be spoken
        """
        self.get_logger().info(f"[VOICE]: {text}")
Member Data Documentation
mode
str home_robot.navigation_manager.NavigationManager.mode = self.get_parameter('mode').get_parameter_value().string_value
Definition at line 42 of file navigation_manager.py.
Referenced by run().
navigator
home_robot.navigation_manager.NavigationManager.navigator = BasicNavigator()
Definition at line 44 of file navigation_manager.py.
Referenced by run().
waypoints
dict home_robot.navigation_manager.NavigationManager.waypoints = self.load_waypoints()
Definition at line 47 of file navigation_manager.py.
Referenced by run().
waypoints_path
home_robot.navigation_manager.NavigationManager.waypoints_path = self.get_parameter('waypoints_file').get_parameter_value().string_value
Definition at line 41 of file navigation_manager.py.
Referenced by load_waypoints().
The documentation for this class was generated from the following file:
ros2_ws/src/home_robot/home_robot/navigation_manager.py