Home Robot: A ROS 2 Jazzy package for Service Robotics Course at University of León: home_robot.odom_to_tf.OdomToTF Class Reference
home_robot.odom_to_tf.OdomToTF Class Reference
Node that publishes TF transforms from odometry messages.
Public Member Functions
__init__ (self)
Initialize the OdomToTF node.
None odom_callback (self, Odometry msg)
Process odometry message and publish TF transform.
Public Attributes
br = TransformBroadcaster(self)
sub = self.create_subscription(Odometry, '/odom', self.odom_callback, 50)
Detailed Description
Node that publishes TF transforms from odometry messages.
Definition at line 16 of file odom_to_tf.py.
Constructor & Destructor Documentation
__init__()
home_robot.odom_to_tf.OdomToTF.__init__ (self)
Initialize the OdomToTF node.
Definition at line 19 of file odom_to_tf.py.
    def __init__(self):
        """Initialize the OdomToTF node."""
        super().__init__('odom_to_tf')
        # Do not hardcode child_frame_id; extract it from the /odom message
        self.br = TransformBroadcaster(self)
        self.sub = self.create_subscription(Odometry, '/odom', self.odom_callback, 50)
        self.get_logger().info("Publishing TF from /odom (odom -> child_frame_id from msg)")
References __init__().
Referenced by __init__().
Member Function Documentation
odom_callback()
None home_robot.odom_to_tf.OdomToTF.odom_callback (self, Odometry msg)
Process odometry message and publish TF transform.
Args: msg: Odometry message containing pose and frame information.
Definition at line 28 of file odom_to_tf.py.
    def odom_callback(self, msg: Odometry) -> None:
        """Process odometry message and publish TF transform.
        Args:
            msg: Odometry message containing pose and frame information.
        """
        t = TransformStamped()
        t.header.stamp = msg.header.stamp
        t.header.frame_id = msg.header.frame_id or "odom"
        t.child_frame_id = msg.child_frame_id or "base_footprint"
        t.transform.translation.x = msg.pose.pose.position.x
        t.transform.translation.y = msg.pose.pose.position.y
        t.transform.translation.z = msg.pose.pose.position.z
        t.transform.rotation = msg.pose.pose.orientation
        self.br.sendTransform(t)
References br.
Member Data Documentation
br
home_robot.odom_to_tf.OdomToTF.br = TransformBroadcaster(self)
Definition at line 24 of file odom_to_tf.py.
Referenced by odom_callback().
sub
home_robot.odom_to_tf.OdomToTF.sub = self.create_subscription(Odometry, '/odom', self.odom_callback, 50)
Definition at line 25 of file odom_to_tf.py.
The documentation for this class was generated from the following file:
ros2_ws/src/home_robot/home_robot/odom_to_tf.py