var searchData=
[
  ['half_5fgrid_0',['half_grid',['../classhome__robot_1_1lidar__grid__node_1_1LidarGridNode.html#ab9b15467438bd322454dfa16ddf63910',1,'home_robot::lidar_grid_node::LidarGridNode']]],
  ['handle_5ferror_1',['4. &lt;span class=&quot;tt&quot;&gt;HANDLE_ERROR&lt;/span&gt;',['../md_docs_2fsm__info.html#autotoc_md31',1,'']]],
  ['handleerrorstate_2',['HandleErrorState',['../classhome__robot__fsm_1_1fsm__patrol_1_1HandleErrorState.html',1,'home_robot_fsm::fsm_patrol']]],
  ['handlefailure_3',['HandleFailure',['../classHandleFailure.html',1,'HandleFailure'],['../classhome__robot__bt_1_1bt__patrol_1_1HandleFailure.html',1,'home_robot_bt.bt_patrol.HandleFailure'],['../classHandleFailure.html#ac207ff659f6d1500be6ad55361bc9c6d',1,'HandleFailure::HandleFailure()']]],
  ['handler_4',['Handler',['../classhome__robot__pddl_1_1pddl__ui__server_1_1Handler.html',1,'home_robot_pddl::pddl_ui_server']]],
  ['hardware_20arduino_5',['Hardware (Arduino)',['../index.html#autotoc_md4',1,'']]],
  ['hardware_20components_20for_20home_20robot_20arduino_20based_20hardware_20interface_6',['Hardware Components for Home Robot Arduino-based Hardware Interface',['../md_docs_2hardware-components.html',1,'']]],
  ['hardware_20interface_7',['Hardware Components for Home Robot Arduino-based Hardware Interface',['../md_docs_2hardware-components.html',1,'']]],
  ['hardware_20tools_8',['🛠️ Hardware &amp;amp; Tools',['../md_docs_2commands.html#autotoc_md21',1,'']]],
  ['hardware_2dcomponents_2emd_9',['hardware-components.md',['../hardware-components_8md.html',1,'']]],
  ['hasarg_10',['hasArg',['../bt__patrol_8cpp.html#a119331c078482772a1a56f94a17b1cbf',1,'bt_patrol.cpp']]],
  ['home_20robot_20arduino_20based_20hardware_20interface_11',['Hardware Components for Home Robot Arduino-based Hardware Interface',['../md_docs_2hardware-components.html',1,'']]],
  ['home_20robot_20navigation_20system_20command_20reference_12',['Home Robot Navigation System - Command Reference',['../md_docs_2commands.html',1,'']]],
  ['home_20robot_3a_20a_20ros_202_20jazzy_20package_20for_20service_20robotics_20course_20at_20university_20of_20león_13',['Home Robot: A ROS 2 Jazzy package for Service Robotics Course at University of León',['../index.html',1,'']]],
  ['home_5frobot_14',['home_robot',['../namespacehome__robot.html',1,'']]],
  ['home_5frobot_3a_3aexecute_5fpatrol_15',['execute_patrol',['../namespacehome__robot_1_1execute__patrol.html',1,'home_robot']]],
  ['home_5frobot_3a_3alidar_5fgrid_5fnode_16',['lidar_grid_node',['../namespacehome__robot_1_1lidar__grid__node.html',1,'home_robot']]],
  ['home_5frobot_3a_3anavigation_5fmanager_17',['navigation_manager',['../namespacehome__robot_1_1navigation__manager.html',1,'home_robot']]],
  ['home_5frobot_3a_3anavigation_5fservice_18',['navigation_service',['../namespacehome__robot_1_1navigation__service.html',1,'home_robot']]],
  ['home_5frobot_3a_3aodom_5fto_5ftf_19',['odom_to_tf',['../namespacehome__robot_1_1odom__to__tf.html',1,'home_robot']]],
  ['home_5frobot_3a_3aoverhead_5fcam_5fservice_20',['overhead_cam_service',['../namespacehome__robot_1_1overhead__cam__service.html',1,'home_robot']]],
  ['home_5frobot_3a_3avoice_5fcontroller_21',['voice_controller',['../namespacehome__robot_1_1voice__controller.html',1,'home_robot']]],
  ['home_5frobot_5fbt_22',['home_robot_bt',['../namespacehome__robot__bt.html',1,'']]],
  ['home_5frobot_5fbt_3a_3abt_5fpatrol_23',['bt_patrol',['../namespacehome__robot__bt_1_1bt__patrol.html',1,'home_robot_bt']]],
  ['home_5frobot_5ffsm_24',['home_robot_fsm',['../namespacehome__robot__fsm.html',1,'']]],
  ['home_5frobot_5ffsm_3a_3afsm_5fpatrol_25',['fsm_patrol',['../namespacehome__robot__fsm_1_1fsm__patrol.html',1,'home_robot_fsm']]],
  ['home_5frobot_5fpddl_26',['home_robot_pddl',['../namespacehome__robot__pddl.html',1,'']]],
  ['home_5frobot_5fpddl_3a_3apddl_5fpatrol_27',['pddl_patrol',['../namespacehome__robot__pddl_1_1pddl__patrol.html',1,'home_robot_pddl']]],
  ['home_5frobot_5fpddl_3a_3apddl_5fui_5fserver_28',['pddl_ui_server',['../namespacehome__robot__pddl_1_1pddl__ui__server.html',1,'home_robot_pddl']]],
  ['home_5frobot_5fpddl_3a_3aproblem_5fgenerator_29',['problem_generator',['../namespacehome__robot__pddl_1_1problem__generator.html',1,'home_robot_pddl']]]
];
